language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn --frozen-lockfile
before_script:
  - node -v
  - yarn -v
script: yarn validate
after_success: npx codecov
branches:
  only:
    - master
    - /^greenkeeper/.*$/
