language: node_js
node_js:
  - "10"
install: yarn --frozen-lockfile
before_script:
  - node -v
  - yarn -v
script: yarn ci
branches:
  only:
    - master

before_deploy:
  - yarn global add netlify-cli
  - yarn build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN ./public
  skip_cleanup: true
  on:
    branch: master
