title: Daniel Lemay | Front End Web Design
description: > # this means to ignore newlines until "baseurl:"
  This site displays some of the recent projects completed by Daniel Lemay as well as a blog with the occassional thoughts.
url: "http://dslemay.com"
timezone: America/Los_Angeles

# Blog settings

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/

paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
