title: Daniel Lemay | Front End Web Developer
description: > # this means to ignore newlines until "baseurl:"
  This site displays some of the recent projects completed by Daniel Lemay as well as a blog with the occassional thoughts.
url: "http://dslemay.com"
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
