
email: daniel@dslemay.com
blurb: "<p><strong>My name is Daniel Lemay, and I am a full stack JavaScript developer who specializes in dynamic and responsive applications.</strong> I love pursuing solutions to complex problems and helping people advance their skills. I pay attention to the details and work well with numerous stakeholders circumventing competing priorities. Take a look at some of my projects and to contact me about available opportunities.</p>"

#-------------------------------
# Portfolio Section

projects:
- {name: "Wanderful", folder: "wanderful"}
- {name: "Simon Game", folder: "simon-game"}
- {name: "Tic Tac Toe Game", folder: "tic-tac-toe"}
- {name: "Pomodoro Timer", folder: "pomodoro-timer"}
- {name: "JavaScript Calculator", folder: "javascript-calculator"}
- {name: "Twitch Viewer", folder: "twitch-viewer"}
- {name: "Wikipedia Viewer", folder: "wikipedia-viewer"}
- {name: "Random Quote Generator", folder: "random-quote-generator"}
